require("prototypes.autoplace-control")
require("prototypes.category")
require("prototypes.entity-changes")
require("prototypes.fluid")
require("prototypes.item")
require("prototypes.item-groups")
require("prototypes.noise-layer")
require("prototypes.particle")
require("prototypes.recipe-changes")
require("prototypes.recipe")
require("prototypes.resource")
require("prototypes.technology")  -- add technology back when all items are created :)
