data:extend({
  -- {
  --   type = "item",
  --   name = "sp-kr-shelter",  -- #ForRegEx# - building
  --   icon = "__Spaghetorio__/graphics/krastorio/icons/entities/shelter.png",
  --   icon_size = 64,
  --   icon_mipmaps = 4,
  --   subgroup = "storage",
  --   order = "aaa",
  --   place_result = "sp-kr-shelter-container",
  --   stack_size = 1,
  -- },
  {
    type = "item",
    name = "sp-medium-storage-tank",
    icon = "__Spaghetorio__/graphics/krastorio/icons/entities/fluid-storages/fluid-storage-1.png",
    stack_size = 50,
    icon_size = 64,
    icon_mipmaps = 4,
    subgroup = "storage",
    order = "b[fluid]-bb2[storage-tank-2]",
    place_result = "sp-medium-storage-tank",
  },
  {
    type = "item",
    name = "sp-large-storage-tank",
    icon = "__Spaghetorio__/graphics/krastorio/icons/entities/fluid-storages/fluid-storage-2.png",
    stack_size = 50,
    icon_size = 64,
    icon_mipmaps = 4,
    subgroup = "storage",
    order = "b[fluid]-c[storage-tank-3]",
    place_result = "sp-large-storage-tank",
  },
})