--  Krastorio Buildings
require("advanced-assembling-machine")
require("advanced-chemical-plant")
require("advanced-furnace")
require("advanced-solar-panel")
require("antimatter-reactor")
require("atmospheric-condenser")
require("big-crusher")
require("genetics-facility")
require("biusart-lab")
require("crystallizer")
require("electrolysis-plant")
require("energy-storage")
require("filtration-plant")
require("fluid-burner")
require("fuel-refinery")
require("gas-power-station")
require("greenhouse")
require("herbarium")
require("incinerator")
require("large-roboport")
require("large-storage-tank")
require("matter-assembler")
require("matter-plant")
require("medium-storage-tank")
require("manufacturer")
-- require("mineral-water-pumpjack")
require("particle-accelerator")
-- require("planetary-teleporter")
require("quantum-computer")
require("quarry-drill")
require("research-server")
-- require("shelter")
require("singularity-beacon")
require("singularity-lab")
require("small-roboport")
require("stabilizer-charging-station")
require("stellar-sinkhole-forge")
require("superior-inserters")
require("wind-turbine")

-- Hurricane046 Buildings
require("alloy-forge")
require("arc-furnace")
require("breeder-reactor")  -- atom forge
require("chemical-stager")
require("core-extractor")
require("cyclotron")  -- fusion reactor
require("freezer")
-- require("geothermal-plant")
require("gravity-assembler")
require("induction-hardening-facility")  -- convector
require("lumber-mill")
require("oxidizer")
require("pathogen-lab")
require("quantum-stabilizer")