local hit_effects = require("__base__/prototypes/entity/hit-effects")
local sounds = require("__base__/prototypes/entity/sounds")

data:extend({

  -- superior-inserter

  {
    type = "inserter",
    name = "kr-superior-inserter",
    icon = "__Spaghetorio__/graphics/krastorio/icons/entities/inserters/superior-inserter.png",
    icon_size = 64,
    icon_mipmaps = 4,
    flags = { "placeable-neutral", "placeable-player", "player-creation" },
    stack = true,
    minable = { mining_time = 0.1, result = "kr-superior-inserter" },
    max_health = 200,
    corpse = "kr-superior-inserter-remnants",
    damaged_trigger_effect = hit_effects.entity(),
    resistances = {
      {
        type = "fire",
        percent = 90,
      },
    },
    collision_box = { { -0.15, -0.15 }, { 0.15, 0.15 } },
    selection_box = { { -0.4, -0.35 }, { 0.4, 0.45 } },
    pickup_position = { 0, -1 },
    insert_position = { 0, 1.2 },
    energy_per_movement = "12KJ",
    energy_per_rotation = "12KJ",
    energy_source = {
      type = "electric",
      usage_priority = "secondary-input",
      drain = "1kW",
    },
    extension_speed = 0.105,
    rotation_speed = 0.06,
    fast_replaceable_group = "inserter",
    vehicle_impact_sound = sounds.generic_impact,
    working_sound = sounds.inserter_fast,
    hand_base_picture = {
      filename = "__Spaghetorio__/graphics/krastorio/entities/superior-inserters/superior-inserter-hand-base.png",
      priority = "extra-high",
      width = 8,
      height = 34,
    },
    hand_closed_picture = {
      filename = "__Spaghetorio__/graphics/krastorio/entities/superior-inserters/superior-inserter/superior-inserter-hand-closed.png",
      priority = "extra-high",
      width = 24,
      height = 41,
    },
    hand_open_picture = {
      filename = "__Spaghetorio__/graphics/krastorio/entities/superior-inserters/superior-inserter/superior-inserter-hand-open.png",
      priority = "extra-high",
      width = 32,
      height = 41,
    },
    hand_base_shadow = {
      filename = "__base__/graphics/entity/burner-inserter/burner-inserter-hand-base-shadow.png",
      priority = "extra-high",
      width = 8,
      height = 33,
    },
    hand_closed_shadow = {
      filename = "__Spaghetorio__/graphics/krastorio/entities/superior-inserters/superior-inserter-hand-closed-shadow.png",
      priority = "extra-high",
      width = 24,
      height = 41,
    },
    hand_open_shadow = {
      filename = "__Spaghetorio__/graphics/krastorio/entities/superior-inserters/superior-inserter-hand-open-shadow.png",
      priority = "extra-high",
      width = 32,
      height = 41,
    },
    platform_picture = {
      sheet = {
        filename = "__Spaghetorio__/graphics/krastorio/entities/superior-inserters/superior-inserter-platform.png",
        priority = "extra-high",
        width = 46,
        height = 46,
        shift = { 0.09375, 0 },
      },
    },
    circuit_wire_connection_points = circuit_connector_definitions["inserter"].points,
    circuit_connector_sprites = circuit_connector_definitions["inserter"].sprites,
    circuit_wire_max_distance = inserter_circuit_wire_max_distance,
    default_stack_control_input_signal = inserter_default_stack_control_input_signal,
  },

  -- superior-long-inserter

  {
    type = "inserter",
    name = "kr-superior-long-inserter",
    icon = "__Spaghetorio__/graphics/krastorio/icons/entities/inserters/superior-long-inserter.png",
    icon_size = 64,
    icon_mipmaps = 4,
    flags = { "placeable-neutral", "placeable-player", "player-creation" },
    stack = true,
    minable = { mining_time = 0.1, result = "kr-superior-long-inserter" },
    max_health = 200,
    corpse = "kr-superior-inserter-remnants",
    damaged_trigger_effect = hit_effects.entity(),
    resistances = {
      {
        type = "fire",
        percent = 90,
      },
    },
    collision_box = { { -0.15, -0.15 }, { 0.15, 0.15 } },
    selection_box = { { -0.4, -0.35 }, { 0.4, 0.45 } },
    pickup_position = { 0, -2 },
    insert_position = { 0, 2.2 },
    energy_per_movement = "13KJ",
    energy_per_rotation = "13KJ",
    energy_source = {
      type = "electric",
      usage_priority = "secondary-input",
      drain = "1kW",
    },
    extension_speed = 0.105,
    rotation_speed = 0.06,
    fast_replaceable_group = "long-handed-inserter",
    vehicle_impact_sound = sounds.generic_impact,
    working_sound = sounds.inserter_fast,
    hand_base_picture = {
      filename = "__Spaghetorio__/graphics/krastorio/entities/superior-inserters/superior-inserter-hand-base.png",
      priority = "extra-high",
      width = 8,
      height = 34,
    },
    hand_closed_picture = {
      filename = "__Spaghetorio__/graphics/krastorio/entities/superior-inserters/superior-long-inserter/superior-long-inserter-hand-closed.png",
      priority = "extra-high",
      width = 24,
      height = 41,
    },
    hand_open_picture = {
      filename = "__Spaghetorio__/graphics/krastorio/entities/superior-inserters/superior-long-inserter/superior-long-inserter-hand-open.png",
      priority = "extra-high",
      width = 32,
      height = 41,
    },
    hand_base_shadow = {
      filename = "__base__/graphics/entity/burner-inserter/burner-inserter-hand-base-shadow.png",
      priority = "extra-high",
      width = 8,
      height = 33,
    },
    hand_closed_shadow = {
      filename = "__Spaghetorio__/graphics/krastorio/entities/superior-inserters/superior-inserter-hand-closed-shadow.png",
      priority = "extra-high",
      width = 24,
      height = 41,
    },
    hand_open_shadow = {
      filename = "__Spaghetorio__/graphics/krastorio/entities/superior-inserters/superior-inserter-hand-open-shadow.png",
      priority = "extra-high",
      width = 32,
      height = 41,
    },
    platform_picture = {
      sheet = {
        filename = "__Spaghetorio__/graphics/krastorio/entities/superior-inserters/superior-inserter-platform.png",
        priority = "extra-high",
        width = 46,
        height = 46,
        shift = { 0.09375, 0 },
      },
    },
    circuit_wire_connection_points = circuit_connector_definitions["inserter"].points,
    circuit_connector_sprites = circuit_connector_definitions["inserter"].sprites,
    circuit_wire_max_distance = inserter_circuit_wire_max_distance,
    default_stack_control_input_signal = inserter_default_stack_control_input_signal,
  },

  -- superior-filter-inserter

  {
    type = "inserter",
    name = "kr-superior-filter-inserter",
    icon = "__Spaghetorio__/graphics/krastorio/icons/entities/inserters/superior-filter-inserter.png",
    icon_size = 64,
    icon_mipmaps = 4,
    flags = { "placeable-neutral", "placeable-player", "player-creation" },
    stack = true,
    filter_count = 4,
    minable = { mining_time = 0.1, result = "kr-superior-filter-inserter" },
    max_health = 200,
    corpse = "kr-superior-inserter-remnants",
    damaged_trigger_effect = hit_effects.entity(),
    resistances = {
      {
        type = "fire",
        percent = 90,
      },
    },
    collision_box = { { -0.15, -0.15 }, { 0.15, 0.15 } },
    selection_box = { { -0.4, -0.35 }, { 0.4, 0.45 } },
    pickup_position = { 0, -1 },
    insert_position = { 0, 1.2 },
    energy_per_movement = "15KJ",
    energy_per_rotation = "15KJ",
    energy_source = {
      type = "electric",
      usage_priority = "secondary-input",
      drain = "1kW",
    },
    extension_speed = 0.105,
    rotation_speed = 0.06,
    fast_replaceable_group = "inserter",
    vehicle_impact_sound = sounds.generic_impact,
    working_sound = sounds.inserter_fast,
    hand_base_picture = {
      filename = "__Spaghetorio__/graphics/krastorio/entities/superior-inserters/superior-inserter-hand-base.png",
      priority = "extra-high",
      width = 8,
      height = 34,
    },
    hand_closed_picture = {
      filename = "__Spaghetorio__/graphics/krastorio/entities/superior-inserters/superior-filter-inserter/superior-filter-inserter-hand-closed.png",
      priority = "extra-high",
      width = 24,
      height = 41,
    },
    hand_open_picture = {
      filename = "__Spaghetorio__/graphics/krastorio/entities/superior-inserters/superior-filter-inserter/superior-filter-inserter-hand-open.png",
      priority = "extra-high",
      width = 32,
      height = 41,
    },
    hand_base_shadow = {
      filename = "__base__/graphics/entity/burner-inserter/burner-inserter-hand-base-shadow.png",
      priority = "extra-high",
      width = 8,
      height = 33,
    },
    hand_closed_shadow = {
      filename = "__Spaghetorio__/graphics/krastorio/entities/superior-inserters/superior-inserter-hand-closed-shadow.png",
      priority = "extra-high",
      width = 24,
      height = 41,
    },
    hand_open_shadow = {
      filename = "__Spaghetorio__/graphics/krastorio/entities/superior-inserters/superior-inserter-hand-open-shadow.png",
      priority = "extra-high",
      width = 32,
      height = 41,
    },
    platform_picture = {
      sheet = {
        filename = "__Spaghetorio__/graphics/krastorio/entities/superior-inserters/superior-inserter-platform.png",
        priority = "extra-high",
        width = 46,
        height = 46,
        shift = { 0.09375, 0 },
      },
    },
    circuit_wire_connection_points = circuit_connector_definitions["inserter"].points,
    circuit_connector_sprites = circuit_connector_definitions["inserter"].sprites,
    circuit_wire_max_distance = inserter_circuit_wire_max_distance,
    default_stack_control_input_signal = inserter_default_stack_control_input_signal,
  },

  -- superior-long-filter-inserter

  {
    type = "inserter",
    name = "kr-superior-long-filter-inserter",
    icon = "__Spaghetorio__/graphics/krastorio/icons/entities/inserters/superior-long-filter-inserter.png",
    icon_size = 64,
    icon_mipmaps = 4,
    flags = { "placeable-neutral", "placeable-player", "player-creation" },
    stack = true,
    filter_count = 4,
    minable = { mining_time = 0.1, result = "kr-superior-long-filter-inserter" },
    max_health = 200,
    corpse = "kr-superior-inserter-remnants",
    damaged_trigger_effect = hit_effects.entity(),
    resistances = {
      {
        type = "fire",
        percent = 90,
      },
    },
    collision_box = { { -0.15, -0.15 }, { 0.15, 0.15 } },
    selection_box = { { -0.4, -0.35 }, { 0.4, 0.45 } },
    pickup_position = { 0, -2 },
    insert_position = { 0, 2.2 },
    energy_per_movement = "16KJ",
    energy_per_rotation = "16KJ",
    energy_source = {
      type = "electric",
      usage_priority = "secondary-input",
      drain = "1kW",
    },
    extension_speed = 0.105,
    rotation_speed = 0.06,
    fast_replaceable_group = "long-handed-inserter",
    vehicle_impact_sound = sounds.generic_impact,
    working_sound = sounds.inserter_fast,
    hand_base_picture = {
      filename = "__Spaghetorio__/graphics/krastorio/entities/superior-inserters/superior-inserter-hand-base.png",
      priority = "extra-high",
      width = 8,
      height = 34,
    },
    hand_closed_picture = {
      filename = "__Spaghetorio__/graphics/krastorio/entities/superior-inserters/superior-long-filter-inserter/superior-long-filter-inserter-hand-closed.png",
      priority = "extra-high",
      width = 24,
      height = 41,
    },
    hand_open_picture = {
      filename = "__Spaghetorio__/graphics/krastorio/entities/superior-inserters/superior-long-filter-inserter/superior-long-filter-inserter-hand-open.png",
      priority = "extra-high",
      width = 32,
      height = 41,
    },
    hand_base_shadow = {
      filename = "__base__/graphics/entity/burner-inserter/burner-inserter-hand-base-shadow.png",
      priority = "extra-high",
      width = 8,
      height = 33,
    },
    hand_closed_shadow = {
      filename = "__Spaghetorio__/graphics/krastorio/entities/superior-inserters/superior-inserter-hand-closed-shadow.png",
      priority = "extra-high",
      width = 24,
      height = 41,
    },
    hand_open_shadow = {
      filename = "__Spaghetorio__/graphics/krastorio/entities/superior-inserters/superior-inserter-hand-open-shadow.png",
      priority = "extra-high",
      width = 32,
      height = 41,
    },
    platform_picture = {
      sheet = {
        filename = "__Spaghetorio__/graphics/krastorio/entities/superior-inserters/superior-inserter-platform.png",
        priority = "extra-high",
        width = 46,
        height = 46,
        shift = { 0.09375, 0 },
      },
    },
    circuit_wire_connection_points = circuit_connector_definitions["inserter"].points,
    circuit_connector_sprites = circuit_connector_definitions["inserter"].sprites,
    circuit_wire_max_distance = inserter_circuit_wire_max_distance,
    default_stack_control_input_signal = inserter_default_stack_control_input_signal,
  },
})
