data:extend({
  {
    type = "item",
    name = "sp-breeder-reactor",  -- #ForRegEx# - building
    icon = "__Spaghetorio__/graphics/icons/breeder-reactor.png",
    icon_size = 64,
    icon_mipmaps = 4,
    subgroup = "production-machine",
    order = "d[breeder-reactor]",
    place_result = "sp-breeder-reactor",
    stack_size = 20,
  },
  {
    type = "item",
    name = "sp-quantum-stabilizer",  -- #ForRegEx# - building
    icon = "__Spaghetorio__/graphics/icons/quantum-stabilizer.png",
    icon_size = 64,
    icon_mipmaps = 4,
    subgroup = "production-machine",
    order = "d[quantum-stabilizer]",
    place_result = "sp-quantum-stabilizer",
    stack_size = 20,
  },
  {
    type = "item",
    name = "sp-pathogen-lab",  -- #ForRegEx# - building
    icon = "__Spaghetorio__/graphics/icons/pathogen-lab.png",
    icon_size = 64,
    icon_mipmaps = 4,
    subgroup = "production-machine",
    order = "d[pathogen-lab]",
    place_result = "sp-pathogen-lab",
    stack_size = 20,
  },
  {
    type = "item",
    name = "sp-chemical-stager",  -- #ForRegEx# - building
    icon = "__Spaghetorio__/graphics/icons/chemical-stager.png",
    icon_size = 64,
    icon_mipmaps = 4,
    subgroup = "production-machine",
    order = "d[chemical-stager]",
    place_result = "sp-chemical-stager",
    stack_size = 20,
  },
  {
    type = "item",
    name = "sp-freezer",  -- #ForRegEx# - building
    icon = "__Spaghetorio__/graphics/icons/freezer.png",
    icon_size = 64,
    icon_mipmaps = 4,
    subgroup = "production-machine",
    order = "d[freezer]",
    place_result = "sp-freezer",
    stack_size = 50,
  },
  {
    type = "item",
    name = "sp-gravity-assembler",  -- #ForRegEx# - building
    icon = "__Spaghetorio__/graphics/icons/gravity-assembler.png",
    icon_size = 64,
    icon_mipmaps = 4,
    subgroup = "production-machine",
    order = "d[gravity-assembler]",
    place_result = "sp-gravity-assembler",
    stack_size = 20,
  },
  {
    type = "item",
    name = "sp-manufacturer",  -- #ForRegEx# - building
    icon = "__Spaghetorio__/graphics/icons/manufacturer.png",
    icon_size = 64,
    icon_mipmaps = 4,
    subgroup = "production-machine",
    order = "d[manufacturer]",
    place_result = "sp-manufacturer",
    stack_size = 50,
  },
  {
    type = "item",
    name = "sp-cyclotron",  -- #ForRegEx# - building
    icon = "__Spaghetorio__/graphics/icons/cyclotron.png",
    icon_size = 64,
    icon_mipmaps = 4,
    subgroup = "production-machine",
    order = "d[cyclotron]",
    place_result = "sp-cyclotron",
    stack_size = 20,
  },
  {
    type = "item",
    name = "sp-oxidizer",  -- #ForRegEx# - building
    icon = "__Spaghetorio__/graphics/icons/oxidizer.png",
    icon_size = 64,
    icon_mipmaps = 4,
    subgroup = "production-machine",
    order = "d[oxidizer]",
    place_result = "sp-oxidizer",
    stack_size = 20,
  },
  {
    type = "item",
    name = "sp-induction-hardening-facility",  -- #ForRegEx# - building
    icon = "__Spaghetorio__/graphics/icons/induction-hardening-facility.png",
    icon_size = 64,
    icon_mipmaps = 4,
    subgroup = "production-machine",
    order = "d[induction-hardening-facility]",
    place_result = "sp-induction-hardening-facility",
    stack_size = 20,
  },
  {
    type = "item",
    name = "sp-incinerator",  -- #ForRegEx# - building
    icon = "__Spaghetorio__/graphics/krastorio/icons/entities/gas-power-station.png",
    icon_size = 64,
    icon_mipmaps = 4,
    stack_size = 50,
    subgroup = "production-machine",
    order = "c[solar-panel]-b[gas-power-station]",
    place_result = "sp-incinerator",
  },
  -- {
  --   type = "item",
  --   name = "sp-research-center",  -- #ForRegEx# - building
  --   icon = "__Spaghetorio__/graphics/icons/research-center.png",
  --   icon_size = 64,
  --   icon_mipmaps = 4,
  --   subgroup = "production-machine",
  --   order = "d[research-center]",
  --   -- place_result = "sp-research-center",
  --   stack_size = 50,
  -- },
  -- {
  --   type = "item",
  --   name = "sp-photonic-lab",  -- #ForRegEx# - building
  --   icon = "__Spaghetorio__/graphics/icons/photonic-lab.png",
  --   icon_size = 64,
  --   icon_mipmaps = 4,
  --   subgroup = "production-machine",
  --   order = "d[photonic-lab]",
  --   -- place_result = "sp-photonic-lab",
  --   stack_size = 50,
  -- },
  {
    type = "item",
    name = "sp-lumber-mill",  -- #ForRegEx# - building
    icon = "__Spaghetorio__/graphics/icons/lumber-mill.png",
    icon_size = 64,
    icon_mipmaps = 4,
    subgroup = "production-machine",
    order = "d[lumber-mill]",
    place_result = "sp-lumber-mill",
    stack_size = 50,
  },
  {
    type = "item",
    name = "sp-kr-advanced-assembling-machine",  -- #ForRegEx# - building
    icon = "__Spaghetorio__/graphics/krastorio/icons/entities/advanced-assembling-machine.png",
    icon_size = 64,
    icon_mipmaps = 4,
    subgroup = "production-machine",
    order = "c[assembling-machine-4]",
    place_result = "sp-kr-advanced-assembling-machine",
    stack_size = 50,
  },
  {
    type = "item",
    name = "sp-kr-advanced-chemical-plant",  -- #ForRegEx# - building
    icon = "__Spaghetorio__/graphics/krastorio/icons/entities/advanced-chemical-plant.png",
    icon_size = 64,
    icon_mipmaps = 4,
    subgroup = "production-machine",
    order = "e[chemical-plant]-b[advanced-chemical-plant]",
    place_result = "sp-kr-advanced-chemical-plant",
    stack_size = 50,
  },
  {
    type = "item",
    name = "sp-kr-genetics-facility",  -- #ForRegEx# - building
    icon = "__Spaghetorio__/graphics/krastorio/icons/entities/bio-lab.png",
    icon_size = 64,
    icon_mipmaps = 4,
    subgroup = "production-machine",
    order = "d-g2[genetics-facility]",
    place_result = "sp-kr-genetics-facility",
    stack_size = 50,
  },
  {
    type = "item",
    name = "sp-kr-greenhouse",  -- #ForRegEx# - building
    icon = "__Spaghetorio__/graphics/krastorio/icons/entities/greenhouse.png",
    icon_size = 64,
    icon_mipmaps = 4,
    subgroup = "production-machine",
    order = "d-g1[greenhouse]",
    place_result = "sp-kr-greenhouse",
    stack_size = 50,
  },
  {
    type = "item",
    name = "sp-herbarium",  -- #ForRegEx# - building
    icon = "__Spaghetorio__/graphics/icons/greenhouse.png",
    icon_size = 64,
    icon_mipmaps = 4,
    subgroup = "production-machine",
    order = "d-g1[herbarium]",
    place_result = "sp-herbarium",
    stack_size = 50,
  },
  {
    type = "item",
    name = "sp-kr-research-server",  -- #ForRegEx# - building
    icon = "__Spaghetorio__/graphics/krastorio/icons/entities/research-server.png",
    icon_size = 64,
    icon_mipmaps = 4,
    subgroup = "production-machine",
    order = "f3[research-servers]-a1[research-server]",
    place_result = "sp-kr-research-server",
    stack_size = 50,
  },
  {
    type = "item",
    name = "sp-kr-quantum-computer",  -- #ForRegEx# - building
    icon = "__Spaghetorio__/graphics/krastorio/icons/entities/quantum-computer.png",
    icon_size = 64,
    icon_mipmaps = 4,
    subgroup = "production-machine",
    order = "f3[research-servers]-b1[quantum-computer]",
    place_result = "sp-kr-quantum-computer",
    stack_size = 20,
  },
  {
    type = "item",
    name = "sp-kr-big-crusher",  -- #ForRegEx# - building
    icon = "__Spaghetorio__/graphics/krastorio/icons/entities/crusher.png",
    icon_size = 64,
    icon_mipmaps = 4,
    subgroup = "production-machine",
    order = "d-h1[crusher]",
    place_result = "sp-kr-big-crusher",
    stack_size = 20,
  },
  {
    type = "item",
    name = "sp-kr-fuel-refinery",  -- #ForRegEx# - building
    icon = "__Spaghetorio__/graphics/krastorio/icons/entities/fuel-refinery.png",
    icon_size = 64,
    icon_mipmaps = 4,
    subgroup = "production-machine",
    order = "e[fuel-refinery]",
    place_result = "sp-kr-fuel-refinery",
    stack_size = 50,
  },
  {
    type = "item",
    name = "sp-kr-electrolysis-plant",  -- #ForRegEx# - building
    icon = "__Spaghetorio__/graphics/krastorio/icons/entities/electrolysis-plant.png",
    icon_size = 64,
    icon_mipmaps = 4,
    subgroup = "production-machine",
    order = "e-a1[electrolysis-plant]",
    place_result = "sp-kr-electrolysis-plant",
    stack_size = 50,
  },
  {
    type = "item",
    name = "sp-kr-filtration-plant",  -- #ForRegEx# - building
    icon = "__Spaghetorio__/graphics/krastorio/icons/entities/filtration-plant.png",
    icon_size = 64,
    icon_mipmaps = 4,
    subgroup = "production-machine",
    order = "e-b1[filtration-plant]",
    place_result = "sp-kr-filtration-plant",
    stack_size = 50,
  },
  {
    type = "item",
    name = "sp-kr-atmospheric-condenser",  -- #ForRegEx# - building
    icon = "__Spaghetorio__/graphics/krastorio/icons/entities/atmospheric-condenser.png",
    icon_size = 64,
    icon_mipmaps = 4,
    subgroup = "production-machine",
    order = "e-c1[atmospheric-condenser]",
    place_result = "sp-kr-atmospheric-condenser",
    stack_size = 50,
  },
  {
    type = "item",
    name = "sp-kr-fluid-burner",  -- #ForRegEx# - building
    icon = "__Spaghetorio__/graphics/krastorio/icons/entities/fluid-burner.png",
    icon_size = 64,
    icon_mipmaps = 4,
    subgroup = "production-machine",
    order = "e-d1[fluid-burner]",
    place_result = "sp-kr-fluid-burner",
    stack_size = 50,
  },
  {
    type = "item",
    name = "sp-kr-matter-plant",  -- #ForRegEx# - building
    icon = "__Spaghetorio__/graphics/krastorio/icons/entities/matter-plant.png",
    icon_size = 128,
    icon_mipmaps = 4,
    subgroup = "production-machine",
    order = "i[matter]-a[matter-plant]",
    place_result = "sp-kr-matter-plant",
    stack_size = 10,
  },
  {
    type = "item",
    name = "sp-kr-matter-assembler",  -- #ForRegEx# - building
    icon = "__Spaghetorio__/graphics/krastorio/icons/entities/matter-assembler.png",
    icon_size = 128,
    icon_mipmaps = 4,
    subgroup = "production-machine",
    order = "i[matter]-b[matter-assembler]",
    place_result = "sp-kr-matter-assembler",
    stack_size = 20,
  },
  {
    type = "item",
    name = "sp-kr-stellar-sinkhole-forge",  -- #ForRegEx# - building
    icon = "__Spaghetorio__/graphics/krastorio/icons/entities/intergalactic-transceiver.png",
    icon_size = 64,
    icon_mipmaps = 4,
    subgroup = "production-machine",
    order = "i[matter]-z[stellar-sinkhole-forge]",
    place_result = "sp-kr-stellar-sinkhole-forge",
    stack_size = 10,
  },
  {
    type = "item",
    name = "sp-kr-stabilizer-charging-station",  -- #ForRegEx# - building
    icon = "__Spaghetorio__/graphics/krastorio/icons/entities/stabilizer-charging-station.png",
    icon_size = 128,
    icon_mipmaps = 4,
    subgroup = "production-machine",
    order = "i[matter]-c[stabilizer-charging-station]",
    place_result = "sp-kr-stabilizer-charging-station",
    stack_size = 50,
  },
})