data:extend({
  {
    type = "fluid",
    name = "sp-aqua-regia",  -- #ForRegEx# - fluid
    default_temperature = 25,
    base_color = {r=0.5, g=0.6, b=0.0},
    flow_color = {r=0.5, g=0.6, b=0.0},
    icon = "__Spaghetorio__/graphics/icons/aqua-regia.png",
    icon_size = 64,
    scale = 0.5,
    subgroup = "sp-solution",
    order = "[aqua-regia]",
  },
  {
    type = "fluid",
    name = "sp-vanadium-bearing-solution",  -- #ForRegEx# - fluid
    default_temperature = 25,
    base_color = {r=0.5, g=0.6, b=0.0},
    flow_color = {r=0.5, g=0.6, b=0.0},
    icon = "__Spaghetorio__/graphics/icons/vanadium-bearing-solution.png",
    icon_size = 64,
    scale = 0.5,
    subgroup = "sp-solution",
    order = "[vanadium-bearing-solution]",
  },
  {
    type = "fluid",
    name = "sp-potassium-permanganate-solution",  -- #ForRegEx# - fluid
    default_temperature = 25,
    base_color = {r=0.55, g=0.2, b=1.0},
    flow_color = {r=0.55, g=0.2, b=1.0},
    icon = "__Spaghetorio__/graphics/icons/potassium-permanganate-solution.png",
    icon_size = 64,
    scale = 0.5,
    subgroup = "sp-solution",
    order = "[potassium-permanganate-solution]",
  },
  {
    type = "fluid",
    name = "sp-potassium-dichromate-solution",  -- #ForRegEx# - fluid
    default_temperature = 25,
    base_color = {r=1.0, g=0.4, b=0.0},
    flow_color = {r=1.0, g=0.4, b=0.0},
    icon = "__Spaghetorio__/graphics/icons/potassium-dichromate-solution.png",
    icon_size = 64,
    scale = 0.5,
    subgroup = "sp-solution",
    order = "[potassium-dichromate-solution]",
  },
  {
    type = "fluid",
    name = "sp-sodium-carbonate-solution",  -- #ForRegEx# - fluid
    default_temperature = 25,
    base_color = {r=1.0, g=0.4, b=0.0},
    flow_color = {r=1.0, g=0.4, b=0.0},
    icon = "__Spaghetorio__/graphics/icons/sodium-carbonate-solution.png",
    icon_size = 64,
    scale = 0.5,
    subgroup = "sp-solution",
    order = "[sodium-carbonate-solution]",
  },
  {
    type = "fluid",
    name = "sp-potassium-hydroxide-solution",  -- #ForRegEx# - fluid
    default_temperature = 25,
    base_color = {r=1.0, g=0.4, b=0.0},
    flow_color = {r=1.0, g=0.4, b=0.0},
    icon = "__Spaghetorio__/graphics/icons/potassium-hydroxide-solution.png",
    icon_size = 64,
    scale = 0.5,
    subgroup = "sp-solution",
    order = "[potassium-hydroxide-solution]",
  },
  {
    type = "fluid",
    name = "sp-potassium-hydroxide-solution",  -- #ForRegEx# - fluid
    default_temperature = 25,
    base_color = {r=1.0, g=0.4, b=0.0},
    flow_color = {r=1.0, g=0.4, b=0.0},
    icon = "__Spaghetorio__/graphics/icons/potassium-hydroxide-solution.png",
    icon_size = 64,
    scale = 0.5,
    subgroup = "sp-solution",
    order = "[potassium-hydroxide-solution]",
  },
  {
    type = "fluid",
    name = "sp-calcium-hydroxide-solution",  -- #ForRegEx# - fluid
    default_temperature = 25,
    base_color = {r=1.0, g=0.4, b=0.0},
    flow_color = {r=1.0, g=0.4, b=0.0},
    icon = "__Spaghetorio__/graphics/icons/calcium-hydroxide-solution.png",
    icon_size = 64,
    scale = 0.5,
    subgroup = "sp-solution",
    order = "[calcium-hydroxide-solution]",
  },
  {
    type = "fluid",
    name = "sp-ammonium-perrhenate-solution",  -- #ForRegEx# - fluid
    default_temperature = 25,
    base_color = {r=1.0, g=0.4, b=0.0},
    flow_color = {r=1.0, g=0.4, b=0.0},
    icon = "__Spaghetorio__/graphics/icons/ammonium-perrhenate-solution.png",
    icon_size = 64,
    scale = 0.5,
    subgroup = "sp-solution",
    order = "[ammonium-perrhenate-solution]",
  },
  {
    type = "fluid",
    name = "sp-sodium-hypochlorite-solution",  -- #ForRegEx# - fluid
    default_temperature = 25,
    base_color = {r=1.0, g=0.4, b=0.0},
    flow_color = {r=1.0, g=0.4, b=0.0},
    icon = "__Spaghetorio__/graphics/icons/sodium-hypochlorite-solution.png",
    icon_size = 64,
    scale = 0.5,
    subgroup = "sp-solution",
    order = "[sodium-hypochlorite-solution]",
  },
  {
    type = "fluid",
    name = "sp-potassium-sulfite-solution",  -- #ForRegEx# - fluid
    default_temperature = 25,
    base_color = {r=1.0, g=0.4, b=0.0},
    flow_color = {r=1.0, g=0.4, b=0.0},
    icon = "__Spaghetorio__/graphics/icons/potassium-sulfite-solution.png",
    icon_size = 64,
    scale = 0.5,
    subgroup = "sp-solution",
    order = "[potassium-sulfite-solution]",
  },
  {
    type = "fluid",
    name = "sp-sodium-sulfite-solution",  -- #ForRegEx# - fluid
    default_temperature = 25,
    base_color = {r=1.0, g=0.4, b=0.0},
    flow_color = {r=1.0, g=0.4, b=0.0},
    icon = "__Spaghetorio__/graphics/icons/sodium-sulfite-solution.png",
    icon_size = 64,
    scale = 0.5,
    subgroup = "sp-solution",
    order = "[sodium-sulfite-solution]",
  },
  {
    type = "fluid",
    name = "sp-ammonium-chloride-solution",  -- #ForRegEx# - fluid
    default_temperature = 25,
    base_color = {r=1.0, g=0.4, b=0.0},
    flow_color = {r=1.0, g=0.4, b=0.0},
    icon = "__Spaghetorio__/graphics/icons/ammonium-chloride-solution.png",
    icon_size = 64,
    scale = 0.5,
    subgroup = "sp-solution",
    order = "[ammonium-chloride-solution]",
  },
  {
    type = "fluid",
    name = "sp-ammonium-bisulfate-solution",  -- #ForRegEx# - fluid
    default_temperature = 25,
    base_color = {r=1.0, g=0.4, b=0.0},
    flow_color = {r=1.0, g=0.4, b=0.0},
    icon = "__Spaghetorio__/graphics/icons/ammonium-bisulfate-solution.png",
    icon_size = 64,
    scale = 0.5,
    subgroup = "sp-solution",
    order = "[ammonium-bisulfate-solution]",
  },
  {
    type = "fluid",
    name = "sp-sulfopropyl-metacrylate-potassium-salt-solution",  -- #ForRegEx# - fluid
    default_temperature = 25,
    base_color = {r=1.0, g=0.4, b=0.0},
    flow_color = {r=1.0, g=0.4, b=0.0},
    icon = "__Spaghetorio__/graphics/icons/sulfopropyl-metacrylate-potassium-salt-solution.png",
    icon_size = 64,
    scale = 0.5,
    subgroup = "sp-solution",
    order = "[sulfopropyl-metacrylate-potassium-salt-solution]",
  },
  {
    type = "fluid",
    name = "sp-methylmagnesium-bromide-solution",  -- #ForRegEx# - fluid
    default_temperature = 25,
    base_color = {r=1.0, g=0.4, b=0.0},
    flow_color = {r=1.0, g=0.4, b=0.0},
    icon = "__Spaghetorio__/graphics/icons/methylmagnesium-bromide-solution.png",
    icon_size = 64,
    scale = 0.5,
    subgroup = "sp-solution",
    order = "[methylmagnesium-bromide-solution]",
  },
  {
    type = "fluid",
    name = "sp-ruthenium-amine-solution",  -- #ForRegEx# - fluid
    default_temperature = 25,
    base_color = {r=0.5, g=0.6, b=0.0},
    flow_color = {r=0.5, g=0.6, b=0.0},
    icon = "__Spaghetorio__/graphics/icons/ruthenium-amine-solution.png",
    icon_size = 64,
    scale = 0.5,
    subgroup = "sp-solution",
    order = "[ruthenium-amine-solution]",
  },
  {
    type = "fluid",
    name = "sp-ruthenium-nitrosyl-solution",  -- #ForRegEx# - fluid
    default_temperature = 25,
    base_color = {r=0.5, g=0.6, b=0.0},
    flow_color = {r=0.5, g=0.6, b=0.0},
    icon = "__Spaghetorio__/graphics/icons/ruthenium-nitrosyl-solution.png",
    icon_size = 64,
    scale = 0.5,
    subgroup = "sp-solution",
    order = "[ruthenium-nitrosyl-solution]",
  },
  {
    type = "fluid",
    name = "sp-hexachloroiridium-acid-solution",  -- #ForRegEx# - fluid
    default_temperature = 25,
    base_color = {r=0.5, g=0.6, b=0.0},
    flow_color = {r=0.5, g=0.6, b=0.0},
    icon = "__Spaghetorio__/graphics/icons/hexachloroiridium-acid-solution.png",
    icon_size = 64,
    scale = 0.5,
    subgroup = "sp-solution",
    order = "[hexachloroiridium-acid-solution]",
  },
})