
data.raw.lab["biolab"].inputs = {
  "basic-tech-card",

  "automation-science-pack",
  "logistic-science-pack",
  "military-science-pack",
  "chemical-science-pack",
  "sp-electronic-science-pack-1",
  "sp-geological-science-pack-1",
  "sp-material-science-pack-1",

  "sp-automation-science-pack-2",
  "sp-logistic-science-pack-2",
  "sp-military-science-pack-2",
  "sp-chemical-science-pack-2",
  "sp-electronic-science-pack-2",
  "sp-geological-science-pack-2",
  "sp-material-science-pack-2",
  "space-science-pack",
  "sp-computer-science-pack-2",
  "sp-nuclear-science-pack-2",
  "production-science-pack",
  "utility-science-pack",

  "sp-automation-science-pack-3",
  "sp-logistic-science-pack-3",
  "sp-military-science-pack-3",
  "sp-chemical-science-pack-3",
  "sp-electronic-science-pack-3",
  "sp-geological-science-pack-3",
  "sp-material-science-pack-3",
  "sp-computer-science-pack-3",
  "sp-production-science-pack-3",
  "sp-nuclear-science-pack-3",
}
